Let's first import required libraries:


In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Load Data From CSV File  


In [4]:
churn_dataset = pd.read_csv("/content/ChurnDataset.csv")
churn_dataset.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

<h2 id="preprocessing">Data pre-processing and selection</h2>


In [5]:
churn_dataset = churn_dataset[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
churn_dataset['churn'] = churn_dataset['churn'].astype('int')
churn_dataset.head()

<ipython-input-5-82f30eb8c24b>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  churn_dataset['churn'] = churn_dataset['churn'].astype('int')


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [8]:
print("Shape of the Churn Dataset")
churn_dataset.shape

Shape of the Churn Dataset


(200, 10)

In [9]:
print("Chceking the columns in the churn dataset")
churn_dataset.columns

Chceking the columns in the churn dataset


Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'churn'],
      dtype='object')

Let's define X, and y for our dataset:


In [18]:
X_values = np.asarray(churn_dataset[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X_values

array([[11., 33.,  7., ...,  5.,  5.,  0.],
       [33., 33., 12., ...,  2.,  0.,  0.],
       [23., 30.,  9., ...,  1.,  2.,  0.],
       ...,
       [ 6., 32., 10., ...,  1., 10.,  0.],
       [24., 30.,  0., ...,  4.,  5.,  0.],
       [61., 50., 16., ...,  2., 22.,  1.]])

In [19]:
y_values = np.asarray(churn_dataset['churn'])
y_values

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0])

Also, we normalize the  churn_dataset using standard Scalar


In [20]:
from sklearn import preprocessing
X_values = preprocessing.StandardScaler().fit(X).transform(X)
X_values

array([[-1.13518441, -0.62595491, -0.4588971 , ...,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, ..., -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , ..., -1.42318853,
        -0.92053635, -0.85972695],
       ...,
       [-1.36680743, -0.7026181 , -0.16283445, ..., -1.42318853,
        -0.02518185, -0.85972695],
       [-0.53296457, -0.85594447, -1.14970993, ...,  0.91629947,
        -0.58477841, -0.85972695],
       [ 1.18104577,  0.67731925,  0.42929083, ..., -0.6433592 ,
         1.31784991,  1.16316   ]])

## Train/Test dataset


We split our dataset into train and test set:


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X_values, y_values, test_size=0.2, random_state=4)
print ('Shape of the Train set:', X_train.shape,  y_train.shape)
print ('Shape of the Test set:', X_test.shape,  y_test.shape)

Shape of the Train set: (160, 7) (160,)
Shape of the Test set: (40, 7) (40,)


<h2 id="modeling">Modeling (Logistic Regression with Scikit-learn)</h2>


In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
Logistic_Regression = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
Logistic_Regression

LogisticRegression(C=0.01, solver='liblinear')

Now we can predict using our test set:


In [24]:
Yprediction = Logistic_Regression .predict(X_test)
print("printing the prediction values")
Yprediction

printing the prediction values


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [26]:
Yprediction_prob = Logistic_Regression.predict_proba(X_test)
Yprediction_prob

array([[0.54132919, 0.45867081],
       [0.60593357, 0.39406643],
       [0.56277713, 0.43722287],
       [0.63432489, 0.36567511],
       [0.56431839, 0.43568161],
       [0.55386646, 0.44613354],
       [0.52237207, 0.47762793],
       [0.60514349, 0.39485651],
       [0.41069572, 0.58930428],
       [0.6333873 , 0.3666127 ],
       [0.58068791, 0.41931209],
       [0.62768628, 0.37231372],
       [0.47559883, 0.52440117],
       [0.4267593 , 0.5732407 ],
       [0.66172417, 0.33827583],
       [0.55092315, 0.44907685],
       [0.51749946, 0.48250054],
       [0.485743  , 0.514257  ],
       [0.49011451, 0.50988549],
       [0.52423349, 0.47576651],
       [0.61619519, 0.38380481],
       [0.52696302, 0.47303698],
       [0.63957168, 0.36042832],
       [0.52205164, 0.47794836],
       [0.50572852, 0.49427148],
       [0.70706202, 0.29293798],
       [0.55266286, 0.44733714],
       [0.52271594, 0.47728406],
       [0.51638863, 0.48361137],
       [0.71331391, 0.28668609],
       [0.

# Evaluation metrics


In [27]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test,Yprediction,pos_label=0)

0.7058823529411765

In [33]:
from sklearn.metrics import accuracy_score

Accuracy = accuracy_score(y_test,Yprediction)
print("Accuracy of our logistic Regression Model is :", Accuracy)

Accuracy of our logistic Regression Model is : 0.75


### Classification Report



In [35]:
from sklearn.metrics import classification_report

# Generate classification report
report = classification_report(y_test, Yprediction)

# Print classification report
print("Classification Report of our logistic Regression Model is:\n", report)


Classification Report of our logistic Regression Model is:
               precision    recall  f1-score   support

           0       0.73      0.96      0.83        25
           1       0.86      0.40      0.55        15

    accuracy                           0.75        40
   macro avg       0.79      0.68      0.69        40
weighted avg       0.78      0.75      0.72        40



In [37]:
from sklearn.metrics import precision_score, recall_score

# Calculate precision for each class
precision = precision_score(y_test, Yprediction, average=None)

# Calculate recall for each class
recall = recall_score(y_test, Yprediction, average=None)
print("Precision and recall of pur logistic regression model is :")
# Print precision and recall for each class
for i in range(len(precision)):
    print(f"Class {i}: Precision = {precision[i]}, Recall = {recall[i]}")


Precision and recall of pur logistic regression model is :
Class 0: Precision = 0.7272727272727273, Recall = 0.96
Class 1: Precision = 0.8571428571428571, Recall = 0.4
